sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 6
  - 8
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
addons:
  chrome: stable
cache:
  directories:
    - node_modules
script:
  - ./node_modules/.bin/ng test --code-coverage --no-progress --browsers=ChromeHeadless
after_success:
  - npm run semantic-release
